### ISSUE TITLE
Seeing HyperLogLog out of bounds panics for use cases.

### ISSUE THREAD

**Issue by michael-grunder** [crepererum/pdatastructs.rs#74]
Hi,

First of all, thank you for writing this crate, it's awesome.

That said, I'm seeing some HyperLogLog panics from time to time.

The error is always an out of bounds array access, and it will vary depending on how many bits the HyperLogLog was created with and the input data in question.

An example error:
```thread 'main' panicked at 'index out of bounds: the len is 79 but the index is 79', .cargo/registry/src/github.com-1ecc6299db9ec823/pdatastructs-0.6.0/src/hyperloglog.rs:233:35```

You should be able to replicate this error with [this small self contained program](https://gist.github.com/michael-grunder/551f2bbdb0e8eda73270049509018e1a)

Let me know if you need more information or if I'm missing something obvious! 

Cheers,
Mike

**Comment by crepererum** [comment]
Hey @michael-grunder, thanks for the bug report and the code snipped. I've created a PR that fixes the issue. :)
